// AI Accountant web app for the Tally Cloud Workstation.
// HTTPS server (self-signed cert generated by repair.ps1), passcode-protected,
// serving a mobile-first chat UI backed by the Claude-powered agent in lib/.
"use strict";

const https = require("https");
const http = require("http");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const APP_DIR = __dirname;
const DATA_DIR = process.env.TALLY_AI_DATA || "C:\\TallyAI\\data";
const CONFIG_FILE = path.join(DATA_DIR, "config.json");
const CHATS_FILE = path.join(DATA_DIR, "chats.json");
const PFX_FILE = process.env.TALLY_AI_PFX || "C:\\TallyAI\\cert.pfx";
const PORT = Number(process.env.TALLY_AI_PORT || 8444);

fs.mkdirSync(DATA_DIR, { recursive: true });

// --- config / state ---------------------------------------------------------
function loadConfig() {
  try { return JSON.parse(fs.readFileSync(CONFIG_FILE, "utf8")); } catch { return null; }
}
function saveConfig(c) { fs.writeFileSync(CONFIG_FILE, JSON.stringify(c, null, 2)); }
function loadChats() {
  try { return JSON.parse(fs.readFileSync(CHATS_FILE, "utf8")); } catch { return { messages: [] }; }
}
function saveChats(c) { fs.writeFileSync(CHATS_FILE, JSON.stringify(c)); }

let config = loadConfig();
let chats = loadChats();
let busy = false;

// --- auth -------------------------------------------------------------------
function sessionToken(cfg) {
  return crypto.createHmac("sha256", cfg.secret).update("session-v1").digest("hex");
}
function isAuthed(req) {
  if (!config) return false;
  const cookies = req.headers.cookie || "";
  const m = cookies.match(/tally_ai_session=([a-f0-9]+)/);
  if (!m) return false;
  try {
    return crypto.timingSafeEqual(Buffer.from(m[1]), Buffer.from(sessionToken(config)));
  } catch { return false; }
}

// --- helpers ----------------------------------------------------------------
function json(res, code, obj, headers = {}) {
  const body = JSON.stringify(obj);
  res.writeHead(code, { "Content-Type": "application/json", ...headers });
  res.end(body);
}
function readBody(req, limit = 30 * 1024 * 1024) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const parts = [];
    req.on("data", (d) => {
      size += d.length;
      if (size > limit) { reject(new Error("body too large")); req.destroy(); return; }
      parts.push(d);
    });
    req.on("end", () => resolve(Buffer.concat(parts)));
    req.on("error", reject);
  });
}

// Trim history so context stays bounded: keep the last ~40 messages, cutting
// at a plain user turn so tool_use/tool_result pairs are never split.
function trimHistory(messages) {
  if (messages.length <= 60) return messages;
  for (let i = messages.length - 40; i < messages.length; i++) {
    const m = messages[i];
    const plainUser = m.role === "user" &&
      (typeof m.content === "string" ||
        (Array.isArray(m.content) && m.content.every((b) => b.type === "text" || b.type === "image")));
    if (plainUser) return messages.slice(i);
  }
  return messages;
}

// Shape sent to the UI for a draft card (no image data, no internals)
function draftView(d) {
  return {
    id: d.id, status: d.status, createdAt: d.createdAt,
    voucher: d.voucher, newLedgers: d.newLedgers, total: d.total,
    bigAmount: d.bigAmount, verified: d.verified, docCount: (d.pendingDocs || []).length || (d.docPaths || []).length,
  };
}

// --- request handling -------------------------------------------------------
async function handle(req, res) {
  const url = new URL(req.url, "https://localhost");
  try {
    // Static
    if (req.method === "GET" && (url.pathname === "/" || url.pathname === "/index.html")) {
      const html = fs.readFileSync(path.join(APP_DIR, "public", "index.html"));
      res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
      return res.end(html);
    }
    if (req.method === "GET" && url.pathname === "/tailwind.css") {
      const css = fs.readFileSync(path.join(APP_DIR, "public", "tailwind.css"));
      res.writeHead(200, { "Content-Type": "text/css; charset=utf-8", "Cache-Control": "public, max-age=3600" });
      return res.end(css);
    }

    // First-run setup
    if (req.method === "POST" && url.pathname === "/api/setup") {
      if (config && config.apiKey && !isAuthed(req)) return json(res, 403, { error: "already configured" });
      const body = JSON.parse((await readBody(req)).toString());
      if (!body.apiKey || !body.passcode || body.passcode.length < 4) {
        return json(res, 400, { error: "API key and a passcode (4+ characters) are required" });
      }
      config = {
        provider: body.provider || "anthropic",
        model: body.model || "claude-opus-5",
        apiKey: body.apiKey.trim(),
        passcode: body.passcode,
        company: body.company || null,
        secret: (config && config.secret) || crypto.randomBytes(32).toString("hex"),
      };
      saveConfig(config);
      return json(res, 200, { ok: true }, {
        "Set-Cookie": `tally_ai_session=${sessionToken(config)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=2592000`,
      });
    }

    if (req.method === "POST" && url.pathname === "/api/login") {
      if (!config) return json(res, 400, { error: "not configured" });
      const body = JSON.parse((await readBody(req)).toString());
      if (body.passcode !== config.passcode) return json(res, 401, { error: "wrong passcode" });
      return json(res, 200, { ok: true }, {
        "Set-Cookie": `tally_ai_session=${sessionToken(config)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=2592000`,
      });
    }

    if (req.method === "GET" && url.pathname === "/api/status") {
      const tally = require("./lib/tally");
      const { loadKnowledge } = require("./lib/agent");
      const authed = isAuthed(req);
      const base = { configured: Boolean(config && config.apiKey), authed };
      if (!authed) return json(res, 200, base);
      const k = loadKnowledge();
      return json(res, 200, {
        ...base,
        model: config.model,
        provider: config.provider,
        tallyOnline: await tally.isOnline(),
        knowledgeAt: k ? k.at : null,
        messageCount: chats.messages.length,
      });
    }

    // Everything below requires auth
    if (!isAuthed(req)) return json(res, 401, { error: "login required" });

    if (req.method === "POST" && url.pathname === "/api/chat") {
      if (busy) return json(res, 429, { error: "I'm still working on your previous message — one moment." });
      const body = JSON.parse((await readBody(req)).toString());
      const blocks = [];
      for (const img of body.images || []) {
        blocks.push({ type: "image", source: { type: "base64", media_type: img.media_type, data: img.data } });
      }
      if (body.text) blocks.push({ type: "text", text: String(body.text).slice(0, 20000) });
      if (blocks.length === 0) return json(res, 400, { error: "empty message" });

      const { runAgent, buildKnowledge, loadKnowledge } = require("./lib/agent");
      const { getProvider } = require("./lib/llm");
      const draftStore = require("./lib/drafts");

      busy = true;
      try {
        if (!loadKnowledge()) await buildKnowledge().catch(() => {});
        chats.messages.push({ role: "user", content: blocks });
        chats.messages = trimHistory(chats.messages);
        const provider = getProvider(config);
        // Drafts created during this turn get the bill images from this
        // message attached, so confirming files them as documents.
        const newDrafts = [];
        const context = {
          createDraft(spec) {
            const d = draftStore.createDraft({ ...spec, images: body.images || [] });
            newDrafts.push(d);
            return d;
          },
        };
        const { reply, steps } = await runAgent({ provider, config, messages: chats.messages, context });
        saveChats(chats);
        return json(res, 200, { reply, steps, drafts: newDrafts.map(draftView) });
      } finally {
        busy = false;
      }
    }

    if (req.method === "GET" && url.pathname === "/api/drafts") {
      const draftStore = require("./lib/drafts");
      return json(res, 200, { drafts: draftStore.listPending().map(draftView) });
    }

    if (req.method === "POST" && url.pathname === "/api/confirm") {
      const draftStore = require("./lib/drafts");
      const body = JSON.parse((await readBody(req)).toString());
      try {
        const d = await draftStore.confirm(body.draft_id, config);
        return json(res, 200, {
          ok: true, verified: d.verified, marker: d.marker,
          docPaths: d.docPaths || [], draft: draftView(d),
        });
      } catch (err) {
        return json(res, err.code || 500, { error: err.message });
      }
    }

    if (req.method === "POST" && url.pathname === "/api/reject") {
      const draftStore = require("./lib/drafts");
      const body = JSON.parse((await readBody(req)).toString());
      try {
        return json(res, 200, { ok: true, draft: draftView(draftStore.reject(body.draft_id)) });
      } catch (err) {
        return json(res, err.code || 500, { error: err.message });
      }
    }

    if (req.method === "POST" && url.pathname === "/api/refresh") {
      const { buildKnowledge } = require("./lib/agent");
      return json(res, 200, await buildKnowledge());
    }

    if (req.method === "POST" && url.pathname === "/api/logout") {
      return json(res, 200, { ok: true }, {
        "Set-Cookie": "tally_ai_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0",
      });
    }

    if (req.method === "POST" && url.pathname === "/api/reset") {
      chats = { messages: [] };
      saveChats(chats);
      return json(res, 200, { ok: true });
    }

    if (req.method === "GET" && url.pathname === "/api/history") {
      // Only user text/images and assistant text — tool traffic stays internal
      const view = [];
      for (const m of chats.messages) {
        if (m.role === "user" && Array.isArray(m.content)) {
          const text = m.content.filter((b) => b.type === "text").map((b) => b.text).join("\n");
          const imgs = m.content.filter((b) => b.type === "image").length;
          if (text || imgs) view.push({ role: "user", text, images: imgs });
        } else if (m.role === "assistant" && Array.isArray(m.content)) {
          const text = m.content.filter((b) => b.type === "text").map((b) => b.text).join("\n");
          if (text) view.push({ role: "assistant", text });
        }
      }
      return json(res, 200, { messages: view });
    }

    json(res, 404, { error: "not found" });
  } catch (err) {
    console.error(new Date().toISOString(), req.method, url.pathname, err);
    try { json(res, 500, { error: err.message || "server error" }); } catch {}
  }
}

// --- start ------------------------------------------------------------------
let server;
if (fs.existsSync(PFX_FILE)) {
  server = https.createServer({ pfx: fs.readFileSync(PFX_FILE), passphrase: "tallyai" }, handle);
} else {
  console.warn("cert.pfx not found - starting HTTP (repair.ps1 generates the certificate)");
  server = http.createServer(handle);
}
server.listen(PORT, () => console.log(`AI Accountant listening on ${PORT} (${fs.existsSync(PFX_FILE) ? "https" : "http"})`));
