// AI Accountant web app for the Tally Cloud Workstation.
// HTTPS server (self-signed cert generated by repair.ps1), passcode-protected,
// serving a mobile-first chat UI backed by the Claude-powered agent in lib/.
"use strict";

const https = require("https");
const http = require("http");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const APP_DIR = __dirname;
const DATA_DIR = process.env.TALLY_AI_DATA || "C:\\TallyAI\\data";
const CONFIG_FILE = path.join(DATA_DIR, "config.json");
const CHATS_FILE = path.join(DATA_DIR, "chats.json");
const PFX_FILE = process.env.TALLY_AI_PFX || "C:\\TallyAI\\cert.pfx";
const PORT = Number(process.env.TALLY_AI_PORT || 8444);

fs.mkdirSync(DATA_DIR, { recursive: true });

// --- config / state ---------------------------------------------------------
function loadConfig() {
  try { return JSON.parse(fs.readFileSync(CONFIG_FILE, "utf8")); } catch { return null; }
}
function saveConfig(c) { fs.writeFileSync(CONFIG_FILE, JSON.stringify(c, null, 2)); }
function loadChats() {
  try { return JSON.parse(fs.readFileSync(CHATS_FILE, "utf8")); } catch { return { messages: [] }; }
}
function saveChats(c) { fs.writeFileSync(CHATS_FILE, JSON.stringify(c)); }

let config = loadConfig();
let chats = loadChats();
let busy = false;

// --- auth -------------------------------------------------------------------
function sessionToken(cfg) {
  return crypto.createHmac("sha256", cfg.secret).update("session-v1").digest("hex");
}
function isAuthed(req) {
  if (!config) return false;
  const cookies = req.headers.cookie || "";
  const m = cookies.match(/tally_ai_session=([a-f0-9]+)/);
  if (!m) return false;
  try {
    return crypto.timingSafeEqual(Buffer.from(m[1]), Buffer.from(sessionToken(config)));
  } catch { return false; }
}

// --- helpers ----------------------------------------------------------------
function json(res, code, obj, headers = {}) {
  const body = JSON.stringify(obj);
  res.writeHead(code, { "Content-Type": "application/json", ...headers });
  res.end(body);
}
function readBody(req, limit = 30 * 1024 * 1024) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const parts = [];
    req.on("data", (d) => {
      size += d.length;
      if (size > limit) { reject(new Error("body too large")); req.destroy(); return; }
      parts.push(d);
    });
    req.on("end", () => resolve(Buffer.concat(parts)));
    req.on("error", reject);
  });
}

// Trim history so context stays bounded: keep the last ~40 messages, cutting
// at a plain user turn so tool_use/tool_result pairs are never split.
function trimHistory(messages) {
  if (messages.length <= 60) return messages;
  for (let i = messages.length - 40; i < messages.length; i++) {
    const m = messages[i];
    const plainUser = m.role === "user" &&
      (typeof m.content === "string" ||
        (Array.isArray(m.content) && m.content.every((b) => b.type === "text" || b.type === "image")));
    if (plainUser) return messages.slice(i);
  }
  return messages;
}

// --- Read-only document browser roots (no write endpoints exist, by design)
const DOC_ROOTS = {
  documents: { label: "Filed documents", root: process.env.TALLY_DOCS || "C:\\TallyData\\Documents" },
  drive: { label: "Drive inbox", root: "C:\\TallyData\\Drive" },
};
const DOC_TYPES = {
  ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".gif": "image/gif",
  ".webp": "image/webp", ".pdf": "application/pdf", ".txt": "text/plain; charset=utf-8",
  ".csv": "text/csv", ".xml": "text/xml",
};
// Resolve a user-supplied relative path strictly inside the chosen root
function docResolve(rootKey, rel) {
  const r = DOC_ROOTS[rootKey];
  if (!r) return null;
  const rootAbs = path.resolve(r.root);
  const p = path.resolve(rootAbs, rel || ".");
  if (p !== rootAbs && !p.startsWith(rootAbs + path.sep)) return null;
  return p;
}

// Shape sent to the UI for a draft card (no image data, no internals)
function draftView(d) {
  return {
    id: d.id, status: d.status, createdAt: d.createdAt,
    voucher: d.voucher, newLedgers: d.newLedgers, total: d.total,
    bigAmount: d.bigAmount, verified: d.verified, docCount: (d.pendingDocs || []).length || (d.docPaths || []).length,
  };
}

// --- request handling -------------------------------------------------------
async function handle(req, res) {
  const url = new URL(req.url, "https://localhost");
  try {
    // Static
    if (req.method === "GET" && (url.pathname === "/" || url.pathname === "/index.html")) {
      const html = fs.readFileSync(path.join(APP_DIR, "public", "index.html"));
      res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
      return res.end(html);
    }
    if (req.method === "GET" && url.pathname === "/tailwind.css") {
      const css = fs.readFileSync(path.join(APP_DIR, "public", "tailwind.css"));
      res.writeHead(200, { "Content-Type": "text/css; charset=utf-8", "Cache-Control": "public, max-age=3600" });
      return res.end(css);
    }

    // First-run setup
    if (req.method === "POST" && url.pathname === "/api/setup") {
      if (config && config.apiKey && !isAuthed(req)) return json(res, 403, { error: "already configured" });
      const body = JSON.parse((await readBody(req)).toString());
      if (!body.apiKey || !body.passcode || body.passcode.length < 4) {
        return json(res, 400, { error: "API key and a passcode (4+ characters) are required" });
      }
      config = {
        provider: body.provider || "anthropic",
        model: body.model || "claude-opus-5",
        apiKey: body.apiKey.trim(),
        passcode: body.passcode,
        company: body.company || null,
        secret: (config && config.secret) || crypto.randomBytes(32).toString("hex"),
      };
      saveConfig(config);
      return json(res, 200, { ok: true }, {
        "Set-Cookie": `tally_ai_session=${sessionToken(config)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=2592000`,
      });
    }

    if (req.method === "POST" && url.pathname === "/api/login") {
      if (!config) return json(res, 400, { error: "not configured" });
      const body = JSON.parse((await readBody(req)).toString());
      if (body.passcode !== config.passcode) return json(res, 401, { error: "wrong passcode" });
      return json(res, 200, { ok: true }, {
        "Set-Cookie": `tally_ai_session=${sessionToken(config)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=2592000`,
      });
    }

    if (req.method === "GET" && url.pathname === "/api/status") {
      const tally = require("./lib/tally");
      const { loadKnowledge } = require("./lib/agent");
      const authed = isAuthed(req);
      const base = { configured: Boolean(config && config.apiKey), authed };
      if (!authed) return json(res, 200, base);
      const k = loadKnowledge();
      return json(res, 200, {
        ...base,
        model: config.model,
        provider: config.provider,
        tallyOnline: await tally.isOnline(),
        knowledgeAt: k ? k.at : null,
        messageCount: chats.messages.length,
      });
    }

    // Everything below requires auth
    if (!isAuthed(req)) return json(res, 401, { error: "login required" });

    if (req.method === "POST" && url.pathname === "/api/chat") {
      if (busy) return json(res, 429, { error: "I'm still working on your previous message — one moment." });
      const body = JSON.parse((await readBody(req)).toString());
      const blocks = [];
      for (const img of body.images || []) {
        blocks.push({ type: "image", source: { type: "base64", media_type: img.media_type, data: img.data } });
      }
      if (body.text) blocks.push({ type: "text", text: String(body.text).slice(0, 20000) });
      if (blocks.length === 0) return json(res, 400, { error: "empty message" });

      const { runAgent, buildKnowledge, loadKnowledge } = require("./lib/agent");
      const { getProvider } = require("./lib/llm");
      const draftStore = require("./lib/drafts");

      busy = true;
      try {
        if (!loadKnowledge()) await buildKnowledge().catch(() => {});
        chats.messages.push({ role: "user", content: blocks });
        chats.messages = trimHistory(chats.messages);
        const provider = getProvider(config);
        // Drafts created during this turn get the bill images from this
        // message attached, so confirming files them as documents.
        const newDrafts = [];
        const context = {
          createDraft(spec) {
            const d = draftStore.createDraft({ ...spec, images: body.images || [] });
            newDrafts.push(d);
            return d;
          },
        };
        const { reply, steps } = await runAgent({ provider, config, messages: chats.messages, context });
        saveChats(chats);
        return json(res, 200, { reply, steps, drafts: newDrafts.map(draftView) });
      } finally {
        busy = false;
      }
    }

    if (req.method === "GET" && url.pathname === "/api/drafts") {
      const draftStore = require("./lib/drafts");
      return json(res, 200, { drafts: draftStore.listPending().map(draftView) });
    }

    if (req.method === "POST" && url.pathname === "/api/confirm") {
      const draftStore = require("./lib/drafts");
      const body = JSON.parse((await readBody(req)).toString());
      try {
        const d = await draftStore.confirm(body.draft_id, config);
        return json(res, 200, {
          ok: true, verified: d.verified, marker: d.marker,
          docPaths: d.docPaths || [], draft: draftView(d),
        });
      } catch (err) {
        return json(res, err.code || 500, { error: err.message });
      }
    }

    if (req.method === "POST" && url.pathname === "/api/reject") {
      const draftStore = require("./lib/drafts");
      const body = JSON.parse((await readBody(req)).toString());
      try {
        return json(res, 200, { ok: true, draft: draftView(draftStore.reject(body.draft_id)) });
      } catch (err) {
        return json(res, err.code || 500, { error: err.message });
      }
    }

    if (req.method === "POST" && url.pathname === "/api/refresh") {
      const { buildKnowledge } = require("./lib/agent");
      return json(res, 200, await buildKnowledge());
    }

    if (req.method === "POST" && url.pathname === "/api/logout") {
      return json(res, 200, { ok: true }, {
        "Set-Cookie": "tally_ai_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0",
      });
    }

    if (req.method === "POST" && url.pathname === "/api/reset") {
      chats = { messages: [] };
      saveChats(chats);
      return json(res, 200, { ok: true });
    }

    // --- Bank reconciliation ------------------------------------------------
    if (req.method === "POST" && url.pathname === "/api/recon/upload") {
      const recon = require("./lib/recon");
      const tallyLib = require("./lib/tally");
      const { getProvider } = require("./lib/llm");
      const body = JSON.parse((await readBody(req)).toString());
      let lines = null, method = "csv";
      if (body.text) lines = recon.parseCsvStatement(body.text);
      if (!lines) {
        method = "ai-extraction";
        lines = await recon.llmExtract(getProvider(config), body);
      }
      const validation = recon.validateLines(lines);
      const ledgers = await tallyLib.listLedgers().catch(() => []);
      const bankLedgers = ledgers.filter((l) => /bank/i.test(l.group)).map((l) => l.name);
      const dates = lines.map((l) => l.date).sort();
      const session = recon.newSession({
        filename: body.filename || "statement", method, lines, validation,
        from: dates[0], to: dates[dates.length - 1],
      });
      return json(res, 200, {
        reconId: session.id, method, validation,
        from: session.from, to: session.to, lineCount: lines.length,
        bankLedgers: bankLedgers.length ? bankLedgers : ledgers.map((l) => l.name).slice(0, 50),
      });
    }

    if (req.method === "POST" && url.pathname === "/api/recon/match") {
      const recon = require("./lib/recon");
      const tallyLib = require("./lib/tally");
      const body = JSON.parse((await readBody(req)).toString());
      const s = recon.getSession(body.reconId);
      if (!s) return json(res, 404, { error: "reconciliation session not found" });
      const pad = (d, days) => {
        const dt = new Date(`${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)}`);
        dt.setDate(dt.getDate() + days);
        return dt.toISOString().slice(0, 10).replace(/-/g, "");
      };
      const day = await tallyLib.dayBook(pad(s.from, -20), pad(s.to, 20), config.company || undefined, { includeRaw: true, limit: 500 });
      const result = require("./lib/recon").matchLines(s.lines, day.vouchers, body.bankLedger);
      s.bankLedger = body.bankLedger;
      s.match = {
        matched: result.matched.map((m) => ({ stmt: m.stmt, reason: m.reason, confidence: m.confidence,
          voucher: { ...m.voucher, raw: undefined }, raw: m.voucher.raw })),
        bankOnly: result.bankOnly, bookOnly: result.bookOnly,
      };
      s.status = "matched";
      recon.saveSession(s);
      const view = {
        reconId: s.id, bankLedger: body.bankLedger,
        matched: s.match.matched.map((m, i) => ({ i, stmt: m.stmt, reason: m.reason, confidence: m.confidence,
          voucher: { date: m.voucher.date, type: m.voucher.type, number: m.voucher.number, narration: m.voucher.narration } })),
        bankOnly: result.bankOnly, bookOnly: result.bookOnly.map((v) => ({ ...v, raw: undefined })),
        truncated: day.truncated,
      };
      return json(res, 200, view);
    }

    if (req.method === "POST" && url.pathname === "/api/recon/apply") {
      const recon = require("./lib/recon");
      const tallyLib = require("./lib/tally");
      const body = JSON.parse((await readBody(req)).toString());
      const s = recon.getSession(body.reconId);
      if (!s || !s.match) return json(res, 404, { error: "no matched session" });
      if (s.status === "applied") return json(res, 409, { error: "ticks were already applied for this reconciliation" });
      const audit = (ev) => fs.appendFileSync(path.join(DATA_DIR, "audit.log"), JSON.stringify({ at: new Date().toISOString(), ...ev }) + "\n");
      const results = [];
      for (const m of s.match.matched) {
        try {
          if (!m.raw) throw new Error("voucher XML missing");
          // Pre-capture the financial fingerprint, alter, then VERIFY nothing
          // but the bank date changed (ADR-0016 safety requirement).
          const before = m.voucher.ledgerEntries.map((e) => `${e.ledger}|${e.amount}`).join(";");
          const r = await tallyLib.setBankDate({ rawVoucherXml: m.raw, bankLedger: s.bankLedger, bankersDate: m.stmt.date, company: config.company || undefined });
          if (!r.ok) throw new Error(r.lineError || "Tally rejected the alteration");
          const check = await tallyLib.dayBook(m.voucher.date, m.voucher.date, config.company || undefined);
          const after = check.vouchers.find((v) => v.number === m.voucher.number && v.narration === m.voucher.narration);
          const afterPrint = after ? after.ledgerEntries.map((e) => `${e.ledger}|${e.amount}`).join(";") : null;
          if (!after || afterPrint !== before) {
            audit({ event: "recon_tick_VERIFY_FAILED", recon: s.id, voucher: m.voucher.number, before, after: afterPrint });
            results.push({ voucher: m.voucher.number, ok: false, error: "post-alter verification failed — STOPPED; check this voucher in Tally" });
            break; // stop the batch immediately on any verification failure
          }
          audit({ event: "recon_tick_applied", recon: s.id, voucher: m.voucher.number, bankDate: m.stmt.date, stmt: m.stmt, reason: m.reason });
          results.push({ voucher: m.voucher.number, ok: true });
        } catch (err) {
          audit({ event: "recon_tick_failed", recon: s.id, voucher: m.voucher && m.voucher.number, error: err.message });
          results.push({ voucher: m.voucher && m.voucher.number, ok: false, error: err.message });
          break;
        }
      }
      const allOk = results.length === s.match.matched.length && results.every((r) => r.ok);
      s.status = allOk ? "applied" : "apply-incomplete";
      s.applyResults = results;
      recon.saveSession(s);
      return json(res, 200, { ok: allOk, results });
    }

    if (req.method === "GET" && url.pathname === "/api/docs") {
      const rootKey = url.searchParams.get("root") || "documents";
      const rel = url.searchParams.get("path") || "";
      const dir = docResolve(rootKey, rel);
      if (!dir) return json(res, 400, { error: "invalid path" });
      if (!fs.existsSync(dir)) return json(res, 200, { entries: [], roots: Object.entries(DOC_ROOTS).map(([k, v]) => ({ key: k, label: v.label })) });
      const entries = fs.readdirSync(dir, { withFileTypes: true })
        .filter((e) => !e.name.startsWith("."))
        .map((e) => {
          const st = fs.statSync(path.join(dir, e.name));
          return { name: e.name, dir: e.isDirectory(), size: st.size, mtime: st.mtimeMs };
        })
        .sort((a, b) => (a.dir !== b.dir ? (a.dir ? -1 : 1) : b.mtime - a.mtime));
      return json(res, 200, { entries, roots: Object.entries(DOC_ROOTS).map(([k, v]) => ({ key: k, label: v.label })) });
    }

    if (req.method === "GET" && url.pathname === "/api/docs/search") {
      const q = url.searchParams.get("q") || "";
      return json(res, 200, { results: require("./lib/docindex").search(q) });
    }

    if (req.method === "GET" && url.pathname === "/api/docs/file") {
      const file = docResolve(url.searchParams.get("root") || "documents", url.searchParams.get("path") || "");
      if (!file || !fs.existsSync(file) || !fs.statSync(file).isFile()) return json(res, 404, { error: "not found" });
      const ext = path.extname(file).toLowerCase();
      const type = DOC_TYPES[ext] || "application/octet-stream";
      const forceDownload = url.searchParams.get("download") === "1" || !DOC_TYPES[ext];
      const name = path.basename(file).replace(/[^\x20-\x7E]/g, "_").replace(/"/g, "");
      res.writeHead(200, {
        "Content-Type": type,
        "Content-Length": fs.statSync(file).size,
        "Content-Disposition": `${forceDownload ? "attachment" : "inline"}; filename="${name}"`,
        "X-Content-Type-Options": "nosniff",
      });
      return fs.createReadStream(file).pipe(res);
    }

    if (req.method === "GET" && url.pathname === "/api/history") {
      // Only user text/images and assistant text — tool traffic stays internal
      const view = [];
      for (const m of chats.messages) {
        if (m.role === "user" && Array.isArray(m.content)) {
          const text = m.content.filter((b) => b.type === "text").map((b) => b.text).join("\n");
          const imgs = m.content.filter((b) => b.type === "image").length;
          if (text || imgs) view.push({ role: "user", text, images: imgs });
        } else if (m.role === "assistant" && Array.isArray(m.content)) {
          const text = m.content.filter((b) => b.type === "text").map((b) => b.text).join("\n");
          if (text) view.push({ role: "assistant", text });
        }
      }
      return json(res, 200, { messages: view });
    }

    json(res, 404, { error: "not found" });
  } catch (err) {
    console.error(new Date().toISOString(), req.method, url.pathname, err);
    try { json(res, 500, { error: err.message || "server error" }); } catch {}
  }
}

// --- start ------------------------------------------------------------------
let server;
if (fs.existsSync(PFX_FILE)) {
  server = https.createServer({ pfx: fs.readFileSync(PFX_FILE), passphrase: "tallyai" }, handle);
} else {
  console.warn("cert.pfx not found - starting HTTP (repair.ps1 generates the certificate)");
  server = http.createServer(handle);
}
server.listen(PORT, () => console.log(`AI Accountant listening on ${PORT} (${fs.existsSync(PFX_FILE) ? "https" : "http"})`));
